// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: tsdb.proto

package tsdb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregationSpec_AggregationFunc int32

const (
	AggregationSpec_NONE    AggregationSpec_AggregationFunc = 0
	AggregationSpec_SUM     AggregationSpec_AggregationFunc = 1
	AggregationSpec_COUNT   AggregationSpec_AggregationFunc = 2
	AggregationSpec_AVERAGE AggregationSpec_AggregationFunc = 3
	AggregationSpec_MIN     AggregationSpec_AggregationFunc = 4
	AggregationSpec_MAX     AggregationSpec_AggregationFunc = 5
	AggregationSpec_FIRST   AggregationSpec_AggregationFunc = 6
	AggregationSpec_LAST    AggregationSpec_AggregationFunc = 7
)

// Enum value maps for AggregationSpec_AggregationFunc.
var (
	AggregationSpec_AggregationFunc_name = map[int32]string{
		0: "NONE",
		1: "SUM",
		2: "COUNT",
		3: "AVERAGE",
		4: "MIN",
		5: "MAX",
		6: "FIRST",
		7: "LAST",
	}
	AggregationSpec_AggregationFunc_value = map[string]int32{
		"NONE":    0,
		"SUM":     1,
		"COUNT":   2,
		"AVERAGE": 3,
		"MIN":     4,
		"MAX":     5,
		"FIRST":   6,
		"LAST":    7,
	}
)

func (x AggregationSpec_AggregationFunc) Enum() *AggregationSpec_AggregationFunc {
	p := new(AggregationSpec_AggregationFunc)
	*p = x
	return p
}

func (x AggregationSpec_AggregationFunc) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationSpec_AggregationFunc) Descriptor() protoreflect.EnumDescriptor {
	return file_tsdb_proto_enumTypes[0].Descriptor()
}

func (AggregationSpec_AggregationFunc) Type() protoreflect.EnumType {
	return &file_tsdb_proto_enumTypes[0]
}

func (x AggregationSpec_AggregationFunc) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationSpec_AggregationFunc.Descriptor instead.
func (AggregationSpec_AggregationFunc) EnumDescriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{13, 0}
}

type DataPointUpdate_UpdateType int32

const (
	DataPointUpdate_PUT           DataPointUpdate_UpdateType = 0
	DataPointUpdate_DELETE        DataPointUpdate_UpdateType = 1 // Represents a point tombstone
	DataPointUpdate_DELETE_SERIES DataPointUpdate_UpdateType = 2 // New: Represents a series tombstone
	DataPointUpdate_DELETE_RANGE  DataPointUpdate_UpdateType = 3 // New: Represents a range tombstone
)

// Enum value maps for DataPointUpdate_UpdateType.
var (
	DataPointUpdate_UpdateType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
		2: "DELETE_SERIES",
		3: "DELETE_RANGE",
	}
	DataPointUpdate_UpdateType_value = map[string]int32{
		"PUT":           0,
		"DELETE":        1,
		"DELETE_SERIES": 2,
		"DELETE_RANGE":  3,
	}
)

func (x DataPointUpdate_UpdateType) Enum() *DataPointUpdate_UpdateType {
	p := new(DataPointUpdate_UpdateType)
	*p = x
	return p
}

func (x DataPointUpdate_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataPointUpdate_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_tsdb_proto_enumTypes[1].Descriptor()
}

func (DataPointUpdate_UpdateType) Type() protoreflect.EnumType {
	return &file_tsdb_proto_enumTypes[1]
}

func (x DataPointUpdate_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataPointUpdate_UpdateType.Descriptor instead.
func (DataPointUpdate_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{20, 0}
}

// Messages for Put
type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields        *structpb.Struct       `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_tsdb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *PutRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *PutRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PutRequest) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_tsdb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{1}
}

// Request for putting a batch of data points.
type PutBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*PutRequest          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBatchRequest) Reset() {
	*x = PutBatchRequest{}
	mi := &file_tsdb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBatchRequest) ProtoMessage() {}

func (x *PutBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBatchRequest.ProtoReflect.Descriptor instead.
func (*PutBatchRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{2}
}

func (x *PutBatchRequest) GetPoints() []*PutRequest {
	if x != nil {
		return x.Points
	}
	return nil
}

type PutBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBatchResponse) Reset() {
	*x = PutBatchResponse{}
	mi := &file_tsdb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBatchResponse) ProtoMessage() {}

func (x *PutBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBatchResponse.ProtoReflect.Descriptor instead.
func (*PutBatchResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{3}
}

// Messages for Get
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_tsdb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{4}
}

func (x *GetRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *GetRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        *structpb.Struct       `protobuf:"bytes,1,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_tsdb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{5}
}

func (x *GetResponse) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Messages for Delete
type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_tsdb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *DeleteRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DeleteRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_tsdb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{7}
}

// Messages for DeleteSeries
type DeleteSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeriesRequest) Reset() {
	*x = DeleteSeriesRequest{}
	mi := &file_tsdb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeriesRequest) ProtoMessage() {}

func (x *DeleteSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeriesRequest.ProtoReflect.Descriptor instead.
func (*DeleteSeriesRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteSeriesRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *DeleteSeriesRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type DeleteSeriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSeriesResponse) Reset() {
	*x = DeleteSeriesResponse{}
	mi := &file_tsdb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSeriesResponse) ProtoMessage() {}

func (x *DeleteSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSeriesResponse.ProtoReflect.Descriptor instead.
func (*DeleteSeriesResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{9}
}

// Messages for DeleteDataPointsByTimeRange
type DeletesByTimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesByTimeRangeRequest) Reset() {
	*x = DeletesByTimeRangeRequest{}
	mi := &file_tsdb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesByTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesByTimeRangeRequest) ProtoMessage() {}

func (x *DeletesByTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesByTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*DeletesByTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{10}
}

func (x *DeletesByTimeRangeRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *DeletesByTimeRangeRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DeletesByTimeRangeRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *DeletesByTimeRangeRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type DeletesByTimeRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletesByTimeRangeResponse) Reset() {
	*x = DeletesByTimeRangeResponse{}
	mi := &file_tsdb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletesByTimeRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletesByTimeRangeResponse) ProtoMessage() {}

func (x *DeletesByTimeRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletesByTimeRangeResponse.ProtoReflect.Descriptor instead.
func (*DeletesByTimeRangeResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{11}
}

// Messages for Query
type QueryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Metric             string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	StartTime          int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime            int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Tags               map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AggregationSpecs   []*AggregationSpec     `protobuf:"bytes,5,rep,name=aggregation_specs,json=aggregationSpecs,proto3" json:"aggregation_specs,omitempty"`
	DownsampleInterval string                 `protobuf:"bytes,6,opt,name=downsample_interval,json=downsampleInterval,proto3" json:"downsample_interval,omitempty"`
	EmitEmptyWindows   bool                   `protobuf:"varint,7,opt,name=emit_empty_windows,json=emitEmptyWindows,proto3" json:"emit_empty_windows,omitempty"`
	// The maximum number of results (data points or windows) to return. 0 means no limit.
	Limit         int64 `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_tsdb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{12}
}

func (x *QueryRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *QueryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *QueryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *QueryRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryRequest) GetAggregationSpecs() []*AggregationSpec {
	if x != nil {
		return x.AggregationSpecs
	}
	return nil
}

func (x *QueryRequest) GetDownsampleInterval() string {
	if x != nil {
		return x.DownsampleInterval
	}
	return ""
}

func (x *QueryRequest) GetEmitEmptyWindows() bool {
	if x != nil {
		return x.EmitEmptyWindows
	}
	return false
}

func (x *QueryRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// AggregationSpec defines a single aggregation function to be applied.
type AggregationSpec struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Function      AggregationSpec_AggregationFunc `protobuf:"varint,1,opt,name=function,proto3,enum=tsdb.AggregationSpec_AggregationFunc" json:"function,omitempty"`
	Field         string                          `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"` // The field to aggregate on, or "*" for count(*)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AggregationSpec) Reset() {
	*x = AggregationSpec{}
	mi := &file_tsdb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregationSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregationSpec) ProtoMessage() {}

func (x *AggregationSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregationSpec.ProtoReflect.Descriptor instead.
func (*AggregationSpec) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{13}
}

func (x *AggregationSpec) GetFunction() AggregationSpec_AggregationFunc {
	if x != nil {
		return x.Function
	}
	return AggregationSpec_NONE
}

func (x *AggregationSpec) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

// QueryResult represents a single data point or aggregated result from a query. (FR1.4)
type QueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Common fields for both raw and aggregated results
	Metric string            `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags   map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Tags for the series
	// Fields for raw data points (if is_aggregated is false)
	Timestamp int64            `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Fields    *structpb.Struct `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	// Fields for aggregated results (if is_aggregated is true)
	WindowStartTime  int64              `protobuf:"varint,5,opt,name=window_start_time,json=windowStartTime,proto3" json:"window_start_time,omitempty"`
	WindowEndTime    int64              `protobuf:"varint,6,opt,name=window_end_time,json=windowEndTime,proto3" json:"window_end_time,omitempty"`
	AggregatedValues map[string]float64 `protobuf:"bytes,7,rep,name=aggregated_values,json=aggregatedValues,proto3" json:"aggregated_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // e.g., "avg": 12.5, "sum": 50.0
	IsAggregated     bool               `protobuf:"varint,8,opt,name=is_aggregated,json=isAggregated,proto3" json:"is_aggregated,omitempty"`                                                                                        // True if this result represents an aggregated window
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_tsdb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResult) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *QueryResult) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *QueryResult) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *QueryResult) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryResult) GetWindowStartTime() int64 {
	if x != nil {
		return x.WindowStartTime
	}
	return 0
}

func (x *QueryResult) GetWindowEndTime() int64 {
	if x != nil {
		return x.WindowEndTime
	}
	return 0
}

func (x *QueryResult) GetAggregatedValues() map[string]float64 {
	if x != nil {
		return x.AggregatedValues
	}
	return nil
}

func (x *QueryResult) GetIsAggregated() bool {
	if x != nil {
		return x.IsAggregated
	}
	return false
}

// Messages for CreateSnapshot
type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The directory where the snapshot will be stored.
	// This path is relative to a base directory configured on the server.
	SnapshotDir   string `protobuf:"bytes,1,opt,name=snapshot_dir,json=snapshotDir,proto3" json:"snapshot_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_tsdb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSnapshotRequest) GetSnapshotDir() string {
	if x != nil {
		return x.SnapshotDir
	}
	return ""
}

type CreateSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_tsdb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{16}
}

// Messages for GetSeriesByTags (FR1.6)
type GetSeriesByTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        string                 `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesByTagsRequest) Reset() {
	*x = GetSeriesByTagsRequest{}
	mi := &file_tsdb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesByTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesByTagsRequest) ProtoMessage() {}

func (x *GetSeriesByTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesByTagsRequest.ProtoReflect.Descriptor instead.
func (*GetSeriesByTagsRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{17}
}

func (x *GetSeriesByTagsRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *GetSeriesByTagsRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetSeriesByTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeriesKeys    []string               `protobuf:"bytes,1,rep,name=series_keys,json=seriesKeys,proto3" json:"series_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSeriesByTagsResponse) Reset() {
	*x = GetSeriesByTagsResponse{}
	mi := &file_tsdb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSeriesByTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSeriesByTagsResponse) ProtoMessage() {}

func (x *GetSeriesByTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSeriesByTagsResponse.ProtoReflect.Descriptor instead.
func (*GetSeriesByTagsResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{18}
}

func (x *GetSeriesByTagsResponse) GetSeriesKeys() []string {
	if x != nil {
		return x.SeriesKeys
	}
	return nil
}

// Messages for Subscribe (real-time updates)
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metric to subscribe to. If empty, subscribes to all metrics.
	Metric string `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	// The tags to filter by. If empty, no tag filtering is applied for the given metric.
	Tags          map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_tsdb_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{19}
}

func (x *SubscribeRequest) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *SubscribeRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// DataPointUpdate represents a real-time change to a data point.
type DataPointUpdate struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UpdateType    DataPointUpdate_UpdateType `protobuf:"varint,1,opt,name=update_type,json=updateType,proto3,enum=tsdb.DataPointUpdate_UpdateType" json:"update_type,omitempty"`
	Metric        string                     `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	Tags          map[string]string          `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     int64                      `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         float64                    `protobuf:"fixed64,5,opt,name=value,proto3" json:"value,omitempty"` // Value for PUT, can be ignored for DELETE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPointUpdate) Reset() {
	*x = DataPointUpdate{}
	mi := &file_tsdb_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPointUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPointUpdate) ProtoMessage() {}

func (x *DataPointUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPointUpdate.ProtoReflect.Descriptor instead.
func (*DataPointUpdate) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{20}
}

func (x *DataPointUpdate) GetUpdateType() DataPointUpdate_UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return DataPointUpdate_PUT
}

func (x *DataPointUpdate) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *DataPointUpdate) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *DataPointUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DataPointUpdate) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// The request message for ForceFlush.
type ForceFlushRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceFlushRequest) Reset() {
	*x = ForceFlushRequest{}
	mi := &file_tsdb_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceFlushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceFlushRequest) ProtoMessage() {}

func (x *ForceFlushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceFlushRequest.ProtoReflect.Descriptor instead.
func (*ForceFlushRequest) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{21}
}

// The response message for ForceFlush.
type ForceFlushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceFlushResponse) Reset() {
	*x = ForceFlushResponse{}
	mi := &file_tsdb_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceFlushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceFlushResponse) ProtoMessage() {}

func (x *ForceFlushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tsdb_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceFlushResponse.ProtoReflect.Descriptor instead.
func (*ForceFlushResponse) Descriptor() ([]byte, []int) {
	return file_tsdb_proto_rawDescGZIP(), []int{22}
}

var File_tsdb_proto protoreflect.FileDescriptor

const file_tsdb_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tsdb.proto\x12\x04tsdb\x1a\x1cgoogle/protobuf/struct.proto\"\xdc\x01\n" +
	"\n" +
	"PutRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12.\n" +
	"\x04tags\x18\x02 \x03(\v2\x1a.tsdb.PutRequest.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12/\n" +
	"\x06fields\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06fields\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\r\n" +
	"\vPutResponse\";\n" +
	"\x0fPutBatchRequest\x12(\n" +
	"\x06points\x18\x01 \x03(\v2\x10.tsdb.PutRequestR\x06points\"\x12\n" +
	"\x10PutBatchResponse\"\xab\x01\n" +
	"\n" +
	"GetRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12.\n" +
	"\x04tags\x18\x02 \x03(\v2\x1a.tsdb.GetRequest.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\vGetResponse\x12/\n" +
	"\x06fields\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x06fields\"\xb1\x01\n" +
	"\rDeleteRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x121\n" +
	"\x04tags\x18\x02 \x03(\v2\x1d.tsdb.DeleteRequest.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x10\n" +
	"\x0eDeleteResponse\"\x9f\x01\n" +
	"\x13DeleteSeriesRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x127\n" +
	"\x04tags\x18\x02 \x03(\v2#.tsdb.DeleteSeriesRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14DeleteSeriesResponse\"\xe5\x01\n" +
	"\x19DeletesByTimeRangeRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12=\n" +
	"\x04tags\x18\x02 \x03(\v2).tsdb.DeletesByTimeRangeRequest.TagsEntryR\x04tags\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1c\n" +
	"\x1aDeletesByTimeRangeResponse\"\x84\x03\n" +
	"\fQueryRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x120\n" +
	"\x04tags\x18\x04 \x03(\v2\x1c.tsdb.QueryRequest.TagsEntryR\x04tags\x12B\n" +
	"\x11aggregation_specs\x18\x05 \x03(\v2\x15.tsdb.AggregationSpecR\x10aggregationSpecs\x12/\n" +
	"\x13downsample_interval\x18\x06 \x01(\tR\x12downsampleInterval\x12,\n" +
	"\x12emit_empty_windows\x18\a \x01(\bR\x10emitEmptyWindows\x12\x14\n" +
	"\x05limit\x18\b \x01(\x03R\x05limit\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcf\x01\n" +
	"\x0fAggregationSpec\x12A\n" +
	"\bfunction\x18\x01 \x01(\x0e2%.tsdb.AggregationSpec.AggregationFuncR\bfunction\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\"c\n" +
	"\x0fAggregationFunc\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03SUM\x10\x01\x12\t\n" +
	"\x05COUNT\x10\x02\x12\v\n" +
	"\aAVERAGE\x10\x03\x12\a\n" +
	"\x03MIN\x10\x04\x12\a\n" +
	"\x03MAX\x10\x05\x12\t\n" +
	"\x05FIRST\x10\x06\x12\b\n" +
	"\x04LAST\x10\a\"\xf2\x03\n" +
	"\vQueryResult\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12/\n" +
	"\x04tags\x18\x02 \x03(\v2\x1b.tsdb.QueryResult.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12/\n" +
	"\x06fields\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06fields\x12*\n" +
	"\x11window_start_time\x18\x05 \x01(\x03R\x0fwindowStartTime\x12&\n" +
	"\x0fwindow_end_time\x18\x06 \x01(\x03R\rwindowEndTime\x12T\n" +
	"\x11aggregated_values\x18\a \x03(\v2'.tsdb.QueryResult.AggregatedValuesEntryR\x10aggregatedValues\x12#\n" +
	"\ris_aggregated\x18\b \x01(\bR\fisAggregated\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aC\n" +
	"\x15AggregatedValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\":\n" +
	"\x15CreateSnapshotRequest\x12!\n" +
	"\fsnapshot_dir\x18\x01 \x01(\tR\vsnapshotDir\"\x18\n" +
	"\x16CreateSnapshotResponse\"\xa5\x01\n" +
	"\x16GetSeriesByTagsRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x12:\n" +
	"\x04tags\x18\x02 \x03(\v2&.tsdb.GetSeriesByTagsRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\":\n" +
	"\x17GetSeriesByTagsResponse\x12\x1f\n" +
	"\vseries_keys\x18\x01 \x03(\tR\n" +
	"seriesKeys\"\x99\x01\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06metric\x18\x01 \x01(\tR\x06metric\x124\n" +
	"\x04tags\x18\x02 \x03(\v2 .tsdb.SubscribeRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x02\n" +
	"\x0fDataPointUpdate\x12A\n" +
	"\vupdate_type\x18\x01 \x01(\x0e2 .tsdb.DataPointUpdate.UpdateTypeR\n" +
	"updateType\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x123\n" +
	"\x04tags\x18\x03 \x03(\v2\x1f.tsdb.DataPointUpdate.TagsEntryR\x04tags\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x05 \x01(\x01R\x05value\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\n" +
	"UpdateType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\x11\n" +
	"\rDELETE_SERIES\x10\x02\x12\x10\n" +
	"\fDELETE_RANGE\x10\x03\"\x13\n" +
	"\x11ForceFlushRequest\"\x14\n" +
	"\x12ForceFlushResponse2\xc3\x05\n" +
	"\vTSDBService\x12*\n" +
	"\x03Put\x12\x10.tsdb.PutRequest\x1a\x11.tsdb.PutResponse\x129\n" +
	"\bPutBatch\x12\x15.tsdb.PutBatchRequest\x1a\x16.tsdb.PutBatchResponse\x12*\n" +
	"\x03Get\x12\x10.tsdb.GetRequest\x1a\x11.tsdb.GetResponse\x123\n" +
	"\x06Delete\x12\x13.tsdb.DeleteRequest\x1a\x14.tsdb.DeleteResponse\x12E\n" +
	"\fDeleteSeries\x12\x19.tsdb.DeleteSeriesRequest\x1a\x1a.tsdb.DeleteSeriesResponse\x12W\n" +
	"\x12DeletesByTimeRange\x12\x1f.tsdb.DeletesByTimeRangeRequest\x1a .tsdb.DeletesByTimeRangeResponse\x120\n" +
	"\x05Query\x12\x12.tsdb.QueryRequest\x1a\x11.tsdb.QueryResult0\x01\x12K\n" +
	"\x0eCreateSnapshot\x12\x1b.tsdb.CreateSnapshotRequest\x1a\x1c.tsdb.CreateSnapshotResponse\x12N\n" +
	"\x0fGetSeriesByTags\x12\x1c.tsdb.GetSeriesByTagsRequest\x1a\x1d.tsdb.GetSeriesByTagsResponse\x12<\n" +
	"\tSubscribe\x12\x16.tsdb.SubscribeRequest\x1a\x15.tsdb.DataPointUpdate0\x01\x12?\n" +
	"\n" +
	"ForceFlush\x12\x17.tsdb.ForceFlushRequest\x1a\x18.tsdb.ForceFlushResponseb\x06proto3"

var (
	file_tsdb_proto_rawDescOnce sync.Once
	file_tsdb_proto_rawDescData []byte
)

func file_tsdb_proto_rawDescGZIP() []byte {
	file_tsdb_proto_rawDescOnce.Do(func() {
		file_tsdb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tsdb_proto_rawDesc), len(file_tsdb_proto_rawDesc)))
	})
	return file_tsdb_proto_rawDescData
}

var file_tsdb_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tsdb_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_tsdb_proto_goTypes = []any{
	(AggregationSpec_AggregationFunc)(0), // 0: tsdb.AggregationSpec.AggregationFunc
	(DataPointUpdate_UpdateType)(0),      // 1: tsdb.DataPointUpdate.UpdateType
	(*PutRequest)(nil),                   // 2: tsdb.PutRequest
	(*PutResponse)(nil),                  // 3: tsdb.PutResponse
	(*PutBatchRequest)(nil),              // 4: tsdb.PutBatchRequest
	(*PutBatchResponse)(nil),             // 5: tsdb.PutBatchResponse
	(*GetRequest)(nil),                   // 6: tsdb.GetRequest
	(*GetResponse)(nil),                  // 7: tsdb.GetResponse
	(*DeleteRequest)(nil),                // 8: tsdb.DeleteRequest
	(*DeleteResponse)(nil),               // 9: tsdb.DeleteResponse
	(*DeleteSeriesRequest)(nil),          // 10: tsdb.DeleteSeriesRequest
	(*DeleteSeriesResponse)(nil),         // 11: tsdb.DeleteSeriesResponse
	(*DeletesByTimeRangeRequest)(nil),    // 12: tsdb.DeletesByTimeRangeRequest
	(*DeletesByTimeRangeResponse)(nil),   // 13: tsdb.DeletesByTimeRangeResponse
	(*QueryRequest)(nil),                 // 14: tsdb.QueryRequest
	(*AggregationSpec)(nil),              // 15: tsdb.AggregationSpec
	(*QueryResult)(nil),                  // 16: tsdb.QueryResult
	(*CreateSnapshotRequest)(nil),        // 17: tsdb.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),       // 18: tsdb.CreateSnapshotResponse
	(*GetSeriesByTagsRequest)(nil),       // 19: tsdb.GetSeriesByTagsRequest
	(*GetSeriesByTagsResponse)(nil),      // 20: tsdb.GetSeriesByTagsResponse
	(*SubscribeRequest)(nil),             // 21: tsdb.SubscribeRequest
	(*DataPointUpdate)(nil),              // 22: tsdb.DataPointUpdate
	(*ForceFlushRequest)(nil),            // 23: tsdb.ForceFlushRequest
	(*ForceFlushResponse)(nil),           // 24: tsdb.ForceFlushResponse
	nil,                                  // 25: tsdb.PutRequest.TagsEntry
	nil,                                  // 26: tsdb.GetRequest.TagsEntry
	nil,                                  // 27: tsdb.DeleteRequest.TagsEntry
	nil,                                  // 28: tsdb.DeleteSeriesRequest.TagsEntry
	nil,                                  // 29: tsdb.DeletesByTimeRangeRequest.TagsEntry
	nil,                                  // 30: tsdb.QueryRequest.TagsEntry
	nil,                                  // 31: tsdb.QueryResult.TagsEntry
	nil,                                  // 32: tsdb.QueryResult.AggregatedValuesEntry
	nil,                                  // 33: tsdb.GetSeriesByTagsRequest.TagsEntry
	nil,                                  // 34: tsdb.SubscribeRequest.TagsEntry
	nil,                                  // 35: tsdb.DataPointUpdate.TagsEntry
	(*structpb.Struct)(nil),              // 36: google.protobuf.Struct
}
var file_tsdb_proto_depIdxs = []int32{
	25, // 0: tsdb.PutRequest.tags:type_name -> tsdb.PutRequest.TagsEntry
	36, // 1: tsdb.PutRequest.fields:type_name -> google.protobuf.Struct
	2,  // 2: tsdb.PutBatchRequest.points:type_name -> tsdb.PutRequest
	26, // 3: tsdb.GetRequest.tags:type_name -> tsdb.GetRequest.TagsEntry
	36, // 4: tsdb.GetResponse.fields:type_name -> google.protobuf.Struct
	27, // 5: tsdb.DeleteRequest.tags:type_name -> tsdb.DeleteRequest.TagsEntry
	28, // 6: tsdb.DeleteSeriesRequest.tags:type_name -> tsdb.DeleteSeriesRequest.TagsEntry
	29, // 7: tsdb.DeletesByTimeRangeRequest.tags:type_name -> tsdb.DeletesByTimeRangeRequest.TagsEntry
	30, // 8: tsdb.QueryRequest.tags:type_name -> tsdb.QueryRequest.TagsEntry
	15, // 9: tsdb.QueryRequest.aggregation_specs:type_name -> tsdb.AggregationSpec
	0,  // 10: tsdb.AggregationSpec.function:type_name -> tsdb.AggregationSpec.AggregationFunc
	31, // 11: tsdb.QueryResult.tags:type_name -> tsdb.QueryResult.TagsEntry
	36, // 12: tsdb.QueryResult.fields:type_name -> google.protobuf.Struct
	32, // 13: tsdb.QueryResult.aggregated_values:type_name -> tsdb.QueryResult.AggregatedValuesEntry
	33, // 14: tsdb.GetSeriesByTagsRequest.tags:type_name -> tsdb.GetSeriesByTagsRequest.TagsEntry
	34, // 15: tsdb.SubscribeRequest.tags:type_name -> tsdb.SubscribeRequest.TagsEntry
	1,  // 16: tsdb.DataPointUpdate.update_type:type_name -> tsdb.DataPointUpdate.UpdateType
	35, // 17: tsdb.DataPointUpdate.tags:type_name -> tsdb.DataPointUpdate.TagsEntry
	2,  // 18: tsdb.TSDBService.Put:input_type -> tsdb.PutRequest
	4,  // 19: tsdb.TSDBService.PutBatch:input_type -> tsdb.PutBatchRequest
	6,  // 20: tsdb.TSDBService.Get:input_type -> tsdb.GetRequest
	8,  // 21: tsdb.TSDBService.Delete:input_type -> tsdb.DeleteRequest
	10, // 22: tsdb.TSDBService.DeleteSeries:input_type -> tsdb.DeleteSeriesRequest
	12, // 23: tsdb.TSDBService.DeletesByTimeRange:input_type -> tsdb.DeletesByTimeRangeRequest
	14, // 24: tsdb.TSDBService.Query:input_type -> tsdb.QueryRequest
	17, // 25: tsdb.TSDBService.CreateSnapshot:input_type -> tsdb.CreateSnapshotRequest
	19, // 26: tsdb.TSDBService.GetSeriesByTags:input_type -> tsdb.GetSeriesByTagsRequest
	21, // 27: tsdb.TSDBService.Subscribe:input_type -> tsdb.SubscribeRequest
	23, // 28: tsdb.TSDBService.ForceFlush:input_type -> tsdb.ForceFlushRequest
	3,  // 29: tsdb.TSDBService.Put:output_type -> tsdb.PutResponse
	5,  // 30: tsdb.TSDBService.PutBatch:output_type -> tsdb.PutBatchResponse
	7,  // 31: tsdb.TSDBService.Get:output_type -> tsdb.GetResponse
	9,  // 32: tsdb.TSDBService.Delete:output_type -> tsdb.DeleteResponse
	11, // 33: tsdb.TSDBService.DeleteSeries:output_type -> tsdb.DeleteSeriesResponse
	13, // 34: tsdb.TSDBService.DeletesByTimeRange:output_type -> tsdb.DeletesByTimeRangeResponse
	16, // 35: tsdb.TSDBService.Query:output_type -> tsdb.QueryResult
	18, // 36: tsdb.TSDBService.CreateSnapshot:output_type -> tsdb.CreateSnapshotResponse
	20, // 37: tsdb.TSDBService.GetSeriesByTags:output_type -> tsdb.GetSeriesByTagsResponse
	22, // 38: tsdb.TSDBService.Subscribe:output_type -> tsdb.DataPointUpdate
	24, // 39: tsdb.TSDBService.ForceFlush:output_type -> tsdb.ForceFlushResponse
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_tsdb_proto_init() }
func file_tsdb_proto_init() {
	if File_tsdb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tsdb_proto_rawDesc), len(file_tsdb_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tsdb_proto_goTypes,
		DependencyIndexes: file_tsdb_proto_depIdxs,
		EnumInfos:         file_tsdb_proto_enumTypes,
		MessageInfos:      file_tsdb_proto_msgTypes,
	}.Build()
	File_tsdb_proto = out.File
	file_tsdb_proto_goTypes = nil
	file_tsdb_proto_depIdxs = nil
}
